"""student table

Revision ID: 7b1db4d3de7f
Revises: b061282c16ef
Create Date: 2020-08-23 13:53:33.626680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1db4d3de7f'
down_revision = 'b061282c16ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'student_id')
    op.drop_table('student')
    # ### end Alembic commands ###
